source 'https://rubygems.org'

gem 'appium_console'
gem 'appium_lib'
gem 'cpf_faker'
gem 'cucumber'
gem 'faker'
gem 'ostruct'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-checkstyle_formatter'
gem 'selenium-webdriver'
gem 'touch_action'
